import json
import os

from dotenv import load_dotenv
from openai import OpenAI


class WorkerAgent2:
    """
    Worker Agent 2
    ============================================================

    ROLE:
        Transportation, Logistics & Weather Researcher

    RESPONSIBILITIES:
        - Travel time
        - Transportation options
        - Flight/transportation considerations
        - Getting to the destination
        - Getting around the destination
        - Local transportation
        - Weather
        - Seasonal conditions
        - Travel practicality
        - Logistics constraints
        - Safety/logistical considerations
        - Evidence collection

    DOES NOT:
        - Choose the final destination
        - Rank destinations against each other
        - Create the final itinerary
        - Calculate the final trip budget
        - Decide which destination is best
        - Perform Worker 1's destination/experience research

    Main Gemini remains the orchestrator.
    """

    # ==========================================================
    # INITIALIZATION
    # ==========================================================

    def __init__(self):

        load_dotenv()

        # ------------------------------------------------------
        # Worker 2 has its own NVIDIA API key
        # ------------------------------------------------------

        self.api_key = os.getenv(
            "NVIDIA_WORKER2_API_KEY"
        )

        if not self.api_key:
            raise ValueError(
                "NVIDIA_WORKER2_API_KEY is not set in .env"
            )

        # ------------------------------------------------------
        # Worker 2 uses its own NVIDIA model
        # ------------------------------------------------------

        self.model = os.getenv(
            "NVIDIA_WORKER2_MODEL"
        )

        if not self.model:
            raise ValueError(
                "NVIDIA_WORKER2_MODEL is not set in .env"
            )

        # ------------------------------------------------------
        # NVIDIA OpenAI-compatible endpoint
        # ------------------------------------------------------

        self.base_url = os.getenv(
            "NVIDIA_WORKER2_BASE_URL",
            "https://integrate.api.nvidia.com/v1"
        )

        self.client = OpenAI(
            api_key=self.api_key,
            base_url=self.base_url
        )

    # ==========================================================
    # MAIN RESEARCH FUNCTION
    # ==========================================================

    def research(
        self,
        destination,
        country="",
        trip_requirements=None,
        research_questions=None
    ):
        """
        Research transportation, logistics and weather for
        one destination.

        Parameters
        ----------
        destination:
            Destination being researched.

        country:
            Destination country.

        trip_requirements:
            Structured requirements produced by MoodAgent.

        research_questions:
            Questions generated by Main Gemini.

        Returns
        -------
        dict
            Structured logistics research.
        """

        # ------------------------------------------------------
        # Validation
        # ------------------------------------------------------

        if not destination:
            raise ValueError(
                "Destination cannot be empty."
            )

        if trip_requirements is None:
            trip_requirements = {}

        if research_questions is None:
            research_questions = []

        # ------------------------------------------------------
        # Convert inputs to JSON
        # ------------------------------------------------------

        requirements_json = json.dumps(
            trip_requirements,
            ensure_ascii=False,
            indent=2
        )

        questions_json = json.dumps(
            research_questions,
            ensure_ascii=False,
            indent=2
        )

        # ======================================================
        # SYSTEM PROMPT
        # ======================================================

        system_prompt = """
You are Worker Agent 2 in a multi-agent AI travel planning
system.

Your specialization is:

TRANSPORTATION, LOGISTICS AND WEATHER RESEARCH.

You are a specialized research worker.

Your job is to provide structured evidence about how practical
it is to travel to and around ONE destination.

You are NOT the final travel planner.

You are NOT responsible for choosing the best destination.

You must never rank this destination against other destinations.

You must provide information that another AI agent can later
use to compare destinations.

============================================================
IMPORTANT
============================================================

Never invent:

- flight times
- travel times
- transportation schedules
- prices
- weather statistics
- visa requirements
- opening hours
- availability
- routes
- transportation availability

If information is uncertain, explicitly mark it as uncertain.

If current information cannot be verified, do not pretend that
it is current.

Distinguish between:

- general travel information
- seasonal information
- approximate information
- information requiring live verification

Return ONLY valid JSON.
"""

        # ======================================================
        # USER PROMPT
        # ======================================================

        user_prompt = f"""
Research the transportation, logistics and weather situation
for the following destination.

============================================================
DESTINATION
============================================================

Destination:
{destination}

Country:
{country}

============================================================
USER REQUIREMENTS
============================================================

{requirements_json}

============================================================
RESEARCH QUESTIONS
============================================================

{questions_json}

============================================================
RESEARCH AREAS
============================================================

Investigate the following.

------------------------------------------------------------
1. GETTING TO THE DESTINATION
------------------------------------------------------------

Determine the normal ways travelers can reach the destination.

Consider:

- international flights
- domestic flights
- trains
- buses
- ferries
- road travel
- major airports
- major train stations
- major transport hubs

Describe the major practical options.

Do not invent specific flight schedules.

------------------------------------------------------------
2. DEPARTURE LOCATION
------------------------------------------------------------

If the user's departure location is known, consider how
practical the journey is from that location.

Consider:

- number of connections
- typical travel complexity
- major transportation hubs
- whether direct travel is generally possible
- whether multiple transfers are normally required

If the departure location is unknown, say so.

------------------------------------------------------------
3. TRAVEL TIME
------------------------------------------------------------

Research typical travel-time ranges where reliable.

Separate:

- getting to the destination
- getting from the main transport hub into the destination
- local travel

Do NOT claim an exact travel time unless supported by evidence.

Use approximate ranges when appropriate.

------------------------------------------------------------
4. LOCAL TRANSPORTATION
------------------------------------------------------------

Determine how easy it is to move around the destination.

Consider:

- metro/subway
- trains
- buses
- trams
- taxis
- rideshare
- rental cars
- bicycles
- walking
- ferries

Determine whether visitors can reasonably get around without
renting a car.

------------------------------------------------------------
5. TRANSPORTATION PRACTICALITY
------------------------------------------------------------

Assess:

- transportation complexity
- transfer difficulty
- accessibility
- public transportation quality
- dependence on cars
- rural transportation limitations
- transportation convenience for tourists

Do not give a final recommendation.

------------------------------------------------------------
6. WEATHER
------------------------------------------------------------

Research the destination's general climate.

Consider:

- temperature
- rainfall
- humidity
- snow
- sunshine
- seasonal differences
- extreme weather

------------------------------------------------------------
7. SEASONAL WEATHER
------------------------------------------------------------

Explain the general characteristics of:

- spring
- summer
- autumn/fall
- winter

Only provide information that can reasonably be established.

------------------------------------------------------------
8. USER WEATHER PREFERENCE
------------------------------------------------------------

Compare the weather against the user's requirements.

Separate:

MATCHES
PARTIAL MATCHES
CONFLICTS

For example:

If the user wants warm weather and the destination is generally
cold during the requested travel period, identify this as a
conflict.

------------------------------------------------------------
9. TRAVEL DATE COMPATIBILITY
------------------------------------------------------------

If the user supplied travel dates, determine whether the
destination's seasonal conditions are generally compatible.

Do not invent a forecast.

A climate pattern is NOT the same as a weather forecast.

Clearly distinguish them.

------------------------------------------------------------
10. SAFETY AND LOGISTICS
------------------------------------------------------------

Only research broad travel-logistics considerations such as:

- natural weather risks
- transportation difficulties
- road conditions
- seasonal disruptions
- remote-area accessibility

Do not provide unsupported safety claims.

------------------------------------------------------------
11. LOGISTICAL ADVANTAGES
------------------------------------------------------------

List practical advantages.

------------------------------------------------------------
12. LOGISTICAL LIMITATIONS
------------------------------------------------------------

List practical disadvantages.

------------------------------------------------------------
13. UNCERTAINTIES
------------------------------------------------------------

List information that needs live verification.

Examples:

- exact flight schedules
- current transportation schedules
- current weather forecast
- current disruptions
- current visa rules
- current closures

============================================================
OUTPUT
============================================================

Return exactly this JSON structure:

{{
    "destination": "",
    "country": "",

    "getting_there": {{
        "major_airports": [],
        "major_train_stations": [],
        "flight_options": [],
        "train_options": [],
        "bus_options": [],
        "ferry_options": [],
        "road_options": [],
        "general_accessibility": ""
    }},

    "departure_analysis": {{
        "departure_location": "",
        "connection_complexity": "",
        "direct_travel_possible": null,
        "typical_transfer_requirements": [],
        "notes": []
    }},

    "travel_time": {{
        "to_destination": "",
        "from_main_hub": "",
        "local_travel": "",
        "confidence": ""
    }},

    "local_transportation": {{
        "public_transport": [],
        "metro": [],
        "train": [],
        "bus": [],
        "tram": [],
        "taxi": [],
        "rideshare": [],
        "rental_car": [],
        "bicycle": [],
        "walking": [],
        "car_required": null,
        "general_ease": ""
    }},

    "transportation_practicality": {{
        "complexity": "",
        "convenience": "",
        "accessibility": "",
        "car_dependence": "",
        "tourist_friendliness": "",
        "summary": ""
    }},

    "weather": {{
        "climate": "",
        "general_temperature": "",
        "rainfall": "",
        "humidity": "",
        "snow": "",
        "extreme_weather": []
    }},

    "seasonal_weather": {{
        "spring": "",
        "summer": "",
        "autumn": "",
        "winter": ""
    }},

    "travel_date_compatibility": {{
        "travel_dates": "",
        "season": "",
        "compatibility": "",
        "reason": ""
    }},

    "weather_preference_fit": {{
        "matches": [],
        "partial_matches": [],
        "conflicts": []
    }},

    "logistical_advantages": [],

    "logistical_limitations": [],

    "uncertainties": [],

    "evidence": [
        {{
            "claim": "",
            "source": "",
            "source_type": ""
        }}
    ],

    "worker_summary": ""
}}
"""

        # ======================================================
        # MODEL CALL
        # ======================================================

        response = self.client.chat.completions.create(
            model=self.model,

            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ],

            temperature=0.1,

            max_tokens=3000
        )

        # ======================================================
        # EXTRACT RESPONSE
        # ======================================================

        content = (
            response
            .choices[0]
            .message
            .content
        )

        if not content:
            raise ValueError(
                "Worker 2 returned an empty response."
            )

        # ======================================================
        # PARSE JSON
        # ======================================================

        result = self._parse_json(
            content
        )

        # ======================================================
        # BASIC VALIDATION
        # ======================================================

        if not isinstance(
            result,
            dict
        ):
            raise ValueError(
                "Worker 2 returned invalid JSON."
            )

        result.setdefault(
            "destination",
            destination
        )

        result.setdefault(
            "country",
            country
        )

        result.setdefault(
            "logistical_advantages",
            []
        )

        result.setdefault(
            "logistical_limitations",
            []
        )

        result.setdefault(
            "uncertainties",
            []
        )

        result.setdefault(
            "evidence",
            []
        )

        result.setdefault(
            "worker_summary",
            ""
        )

        return result

    # ==========================================================
    # MULTIPLE DESTINATIONS
    # ==========================================================

    def research_multiple(
        self,
        destinations,
        trip_requirements=None,
        research_plan=None
    ):
        """
        Research multiple destinations.

        This is mainly a testing/helper method.

        In production, main.py should run each destination
        concurrently.
        """

        if trip_requirements is None:
            trip_requirements = {}

        if research_plan is None:
            research_plan = {}

        results = []

        for candidate in destinations:

            # --------------------------------------------------
            # Candidate can be a string or dictionary
            # --------------------------------------------------

            if isinstance(
                candidate,
                dict
            ):

                destination = candidate.get(
                    "name",
                    ""
                )

                country = candidate.get(
                    "country",
                    ""
                )

            else:

                destination = str(
                    candidate
                )

                country = ""

            if not destination:
                continue

            # --------------------------------------------------
            # Get questions generated by Main Gemini
            # --------------------------------------------------

            questions = []

            if isinstance(
                research_plan,
                dict
            ):

                questions = research_plan.get(
                    destination,
                    []
                )

            # --------------------------------------------------
            # Research
            # --------------------------------------------------

            try:

                result = self.research(
                    destination=destination,
                    country=country,
                    trip_requirements=
                        trip_requirements,
                    research_questions=
                        questions
                )

                results.append(
                    result
                )

            except Exception as error:

                results.append({

                    "destination":
                        destination,

                    "country":
                        country,

                    "error":
                        str(error)
                })

        return {
            "worker": "worker_2",
            "specialization":
                "transportation_logistics_weather",
            "destinations":
                results
        }

    # ==========================================================
    # JSON PARSER
    # ==========================================================

    @staticmethod
    def _parse_json(
        content
    ):
        """
        Safely parse JSON returned by the model.
        """

        if not isinstance(
            content,
            str
        ):
            raise ValueError(
                "Worker 2 response is not text."
            )

        content = content.strip()

        # ------------------------------------------------------
        # Remove markdown code fences
        # ------------------------------------------------------

        if content.startswith(
            "```"
        ):

            lines = content.splitlines()

            if lines:
                lines = lines[1:]

            if (
                lines
                and
                lines[-1].strip() == "```"
            ):

                lines = lines[:-1]

            content = "\n".join(
                lines
            ).strip()

        # ------------------------------------------------------
        # Direct JSON
        # ------------------------------------------------------

        try:

            return json.loads(
                content
            )

        except json.JSONDecodeError:
            pass

        # ------------------------------------------------------
        # Extract JSON object
        # ------------------------------------------------------

        start = content.find(
            "{"
        )

        end = content.rfind(
            "}"
        )

        if (
            start == -1
            or end == -1
            or end <= start
        ):

            raise ValueError(
                "Worker 2 did not return valid JSON."
            )

        json_text = content[
            start:end + 1
        ]

        try:

            return json.loads(
                json_text
            )

        except json.JSONDecodeError as error:

            raise ValueError(
                f"Worker 2 returned malformed JSON: {error}"
            )