import json
import os

from dotenv import load_dotenv
from openai import OpenAI


class WorkerAgent1:
    """
    Worker Agent 1
    ============================================================

    ROLE:
        Destination & Experience Researcher

    RESPONSIBILITIES:
        - Research destination characteristics
        - Research attractions
        - Research activities
        - Research nature
        - Research culture
        - Research history
        - Research food
        - Research nightlife
        - Research atmosphere
        - Compare destination against user preferences

    DOES NOT:
        - Choose the final destination
        - Rank destinations against each other
        - Build the final itinerary
        - Calculate final trip cost
        - Research transportation
        - Book anything

    The Main Gemini remains the orchestrator.
    """

    # ==========================================================
    # INITIALIZATION
    # ==========================================================

    def __init__(self):

        load_dotenv()

        self.api_key = os.getenv(
            "NVIDIA_API_KEY"
        )

        if not self.api_key:
            raise ValueError(
                "NVIDIA_API_KEY is not set in .env"
            )

        self.model = os.getenv(
            "NVIDIA_WORKER_MODEL",
            "NVIDIABuild-Autogen-23"
        )

        self.base_url = os.getenv(
            "NVIDIA_BASE_URL",
            "https://integrate.api.nvidia.com/v1"
        )

        self.client = OpenAI(
            api_key=self.api_key,
            base_url=self.base_url
        )

    # ==========================================================
    # MAIN RESEARCH FUNCTION
    # ==========================================================

    def research(
        self,
        destination,
        country="",
        trip_requirements=None,
        research_questions=None
    ):
        """
        Research one destination.

        Parameters
        ----------
        destination:
            Destination being researched.

        country:
            Destination country.

        trip_requirements:
            Structured requirements from MoodAgent.

        research_questions:
            Questions generated by Main Gemini.

        Returns
        -------
        dict
            Structured destination research.
        """

        if not destination:
            raise ValueError(
                "Destination cannot be empty."
            )

        if trip_requirements is None:
            trip_requirements = {}

        if research_questions is None:
            research_questions = []

        # ------------------------------------------------------
        # Convert inputs to JSON
        # ------------------------------------------------------

        requirements_json = json.dumps(
            trip_requirements,
            ensure_ascii=False,
            indent=2
        )

        questions_json = json.dumps(
            research_questions,
            ensure_ascii=False,
            indent=2
        )

        # ======================================================
        # SYSTEM PROMPT
        # ======================================================

        system_prompt = """
You are Worker Agent 1 in a multi-agent travel planning system.

Your specialization is:

DESTINATION AND EXPERIENCE RESEARCH.

You are a research worker.

You provide evidence and structured information to another
AI agent.

You are NOT the final decision maker.

You must never decide which destination is the best overall.

You must never compare multiple destinations against each other.

You only investigate the destination provided to you.

Your output must be factual, cautious and structured.

If something cannot be established with reasonable confidence,
say that it is uncertain.

Never invent facts.
Never invent prices.
Never invent statistics.
Never invent opening hours.
Never invent availability.

Return ONLY valid JSON.
"""

        # ======================================================
        # USER PROMPT
        # ======================================================

        user_prompt = f"""
Research the following travel destination.

============================================================
DESTINATION
============================================================

Destination:
{destination}

Country:
{country}

============================================================
USER REQUIREMENTS
============================================================

{requirements_json}

============================================================
RESEARCH QUESTIONS
============================================================

{questions_json}

============================================================
RESEARCH AREAS
============================================================

Investigate:

1. DESTINATION CHARACTER

Determine whether the destination is generally:

- urban
- rural
- coastal
- mountainous
- tropical
- remote
- crowded
- quiet
- relaxed
- adventurous

2. NATURE

Look for:

- mountains
- beaches
- forests
- lakes
- rivers
- wildlife
- national parks
- scenic areas
- hiking
- outdoor activities

3. ATTRACTIONS

Identify important:

- landmarks
- attractions
- viewpoints
- cultural sites
- historical sites
- natural attractions

4. ACTIVITIES

Identify major activities involving:

- sightseeing
- hiking
- nature
- culture
- history
- food
- photography
- nightlife
- adventure
- relaxation
- shopping

5. CULTURE AND HISTORY

Research:

- cultural characteristics
- historical significance
- traditions
- historical landmarks
- important cultural experiences

6. FOOD

Describe the general food culture.

Do NOT invent specific prices.

7. ATMOSPHERE

Determine whether the destination is generally:

- peaceful
- busy
- tourist-heavy
- relaxed
- energetic
- crowded

Mention seasonal variation when relevant.

8. USER PREFERENCE FIT

Determine how the destination relates to the user's
requirements.

Separate:

MATCHES
PARTIAL MATCHES
CONFLICTS

Do not give a final overall recommendation.

9. ADVANTAGES

List important strengths of the destination.

10. LIMITATIONS

List meaningful weaknesses or potential problems.

11. UNCERTAINTIES

List information that should be verified by another research
source or agent.

============================================================
OUTPUT FORMAT
============================================================

Return exactly this JSON structure:

{{
    "destination": "",
    "country": "",

    "destination_character": {{
        "urban": null,
        "rural": null,
        "coastal": null,
        "mountainous": null,
        "tropical": null,
        "remote": null,
        "crowded": null,
        "quiet": null,
        "relaxed": null,
        "adventurous": null
    }},

    "nature": {{
        "mountains": [],
        "beaches": [],
        "forests": [],
        "lakes": [],
        "rivers": [],
        "wildlife": [],
        "national_parks": [],
        "scenic_areas": [],
        "hiking": [],
        "outdoor_activities": []
    }},

    "attractions": [],

    "activities": {{
        "sightseeing": [],
        "culture": [],
        "history": [],
        "food": [],
        "photography": [],
        "nightlife": [],
        "adventure": [],
        "relaxation": [],
        "shopping": []
    }},

    "culture_and_history": {{
        "cultural_features": [],
        "historical_features": [],
        "landmarks": [],
        "traditions": []
    }},

    "food": {{
        "description": "",
        "notable_food_experiences": []
    }},

    "atmosphere": {{
        "description": "",
        "crowd_level": "",
        "tourist_intensity": "",
        "peacefulness": ""
    }},

    "preference_fit": {{
        "matches": [],
        "partial_matches": [],
        "conflicts": []
    }},

    "advantages": [],

    "limitations": [],

    "uncertainties": [],

    "research_questions_answered": [],

    "evidence": [
        {{
            "claim": "",
            "source": "",
            "source_type": ""
        }}
    ],

    "worker_summary": ""
}}
"""

        # ======================================================
        # MODEL CALL
        # ======================================================

        response = self.client.chat.completions.create(
            model=self.model,

            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ],

            temperature=0.1,

            max_tokens=3000
        )

        # ======================================================
        # GET RESPONSE
        # ======================================================

        content = (
            response
            .choices[0]
            .message
            .content
        )

        if not content:
            raise ValueError(
                "Worker 1 returned an empty response."
            )

        # ======================================================
        # PARSE JSON
        # ======================================================

        result = self._parse_json(
            content
        )

        # ======================================================
        # BASIC VALIDATION
        # ======================================================

        if not isinstance(
            result,
            dict
        ):
            raise ValueError(
                "Worker 1 returned invalid JSON."
            )

        result.setdefault(
            "destination",
            destination
        )

        result.setdefault(
            "country",
            country
        )

        result.setdefault(
            "advantages",
            []
        )

        result.setdefault(
            "limitations",
            []
        )

        result.setdefault(
            "uncertainties",
            []
        )

        result.setdefault(
            "evidence",
            []
        )

        result.setdefault(
            "worker_summary",
            ""
        )

        return result

    # ==========================================================
    # MULTIPLE DESTINATIONS
    # ==========================================================

    def research_multiple(
        self,
        destinations,
        trip_requirements=None,
        research_plan=None
    ):
        """
        Test/helper method for researching multiple destinations.

        For production, main.py should execute these calls
        concurrently using ThreadPoolExecutor or asyncio.
        """

        if trip_requirements is None:
            trip_requirements = {}

        if research_plan is None:
            research_plan = {}

        results = []

        for candidate in destinations:

            if isinstance(
                candidate,
                dict
            ):
                destination = candidate.get(
                    "name",
                    ""
                )

                country = candidate.get(
                    "country",
                    ""
                )

            else:
                destination = str(
                    candidate
                )

                country = ""

            if not destination:
                continue

            questions = []

            if isinstance(
                research_plan,
                dict
            ):
                questions = research_plan.get(
                    destination,
                    []
                )

            try:

                result = self.research(
                    destination=destination,
                    country=country,
                    trip_requirements=
                        trip_requirements,
                    research_questions=
                        questions
                )

                results.append(
                    result
                )

            except Exception as error:

                results.append({
                    "destination":
                        destination,
                    "country":
                        country,
                    "error":
                        str(error)
                })

        return results

    # ==========================================================
    # JSON PARSER
    # ==========================================================

    @staticmethod
    def _parse_json(
        content
    ):
        """
        Safely parse JSON from the model response.
        """

        content = content.strip()

        # ------------------------------------------------------
        # Remove markdown fences
        # ------------------------------------------------------

        if content.startswith(
            "```"
        ):

            lines = content.splitlines()

            if lines:
                lines = lines[1:]

            if (
                lines
                and
                lines[-1].strip() == "```"
            ):
                lines = lines[:-1]

            content = "\n".join(
                lines
            ).strip()

        # ------------------------------------------------------
        # Try direct JSON
        # ------------------------------------------------------

        try:

            return json.loads(
                content
            )

        except json.JSONDecodeError:
            pass

        # ------------------------------------------------------
        # Find JSON object inside response
        # ------------------------------------------------------

        start = content.find(
            "{"
        )

        end = content.rfind(
            "}"
        )

        if (
            start == -1
            or end == -1
            or end <= start
        ):
            raise ValueError(
                "Worker 1 did not return valid JSON."
            )

        json_text = content[
            start:end + 1
        ]

        try:

            return json.loads(
                json_text
            )

        except json.JSONDecodeError as error:

            raise ValueError(
                f"Worker 1 returned malformed JSON: {error}"
            )