import json
import os

from dotenv import load_dotenv
from openai import OpenAI


class WorkerAgent3:
    """
    Worker Agent 3
    ============================================================

    ROLE:
        Cost, Budget & Affordability Researcher

    RESPONSIBILITIES:
        - Accommodation costs
        - Food costs
        - Local transportation costs
        - Activity costs
        - General destination affordability
        - Budget compatibility
        - Cost categories
        - Major expensive/cheap aspects
        - Budget risks
        - Evidence collection

    DOES NOT:
        - Choose the final destination
        - Rank destinations against each other
        - Create the final itinerary
        - Make bookings
        - Decide the final winner
        - Perform Worker 1's destination research
        - Perform Worker 2's transportation/weather research

    Main Gemini remains responsible for final decisions.
    """

    # ==========================================================
    # INITIALIZATION
    # ==========================================================

    def __init__(self):

        load_dotenv()

        # ------------------------------------------------------
        # LLM7 API token
        # ------------------------------------------------------

        self.api_key = os.getenv(
            "LLM7_API_TOKEN"
        )

        if not self.api_key:
            raise ValueError(
                "LLM7_API_TOKEN is not set in .env"
            )

        # ------------------------------------------------------
        # LLM7 model
        #
        # "fast" is recommended initially because Worker 3
        # will eventually run many times in parallel.
        #
        # You can replace this with:
        #
        #   default
        #
        # or a specific LLM7 model.
        # ------------------------------------------------------

        self.model = os.getenv(
            "LLM7_WORKER3_MODEL",
            "fast"
        )

        # ------------------------------------------------------
        # LLM7 OpenAI-compatible endpoint
        # ------------------------------------------------------

        self.base_url = os.getenv(
            "LLM7_BASE_URL",
            "https://api.llm7.io/v1"
        )

        self.client = OpenAI(
            base_url=self.base_url,
            api_key=self.api_key
        )

        # ------------------------------------------------------
        # JSON mode
        #
        # LLM7 supports JSON mode on paid plans.
        #
        # We keep this configurable so the worker can also
        # operate using normal prompting if you are using a
        # free token.
        # ------------------------------------------------------

        self.use_json_mode = (
            os.getenv(
                "LLM7_WORKER3_JSON_MODE",
                "false"
            ).lower()
            == "true"
        )

    # ==========================================================
    # MAIN RESEARCH FUNCTION
    # ==========================================================

    def research(
        self,
        destination,
        country="",
        trip_requirements=None,
        research_questions=None
    ):
        """
        Research the cost and budget characteristics of one
        destination.

        Parameters
        ----------
        destination:
            Destination being researched.

        country:
            Destination country.

        trip_requirements:
            Structured requirements from MoodAgent.

        research_questions:
            Questions generated by Main Gemini.

        Returns
        -------
        dict
            Structured cost research.
        """

        # ------------------------------------------------------
        # Validation
        # ------------------------------------------------------

        if not destination:
            raise ValueError(
                "Destination cannot be empty."
            )

        if trip_requirements is None:
            trip_requirements = {}

        if research_questions is None:
            research_questions = []

        # ------------------------------------------------------
        # Convert input to JSON
        # ------------------------------------------------------

        requirements_json = json.dumps(
            trip_requirements,
            ensure_ascii=False,
            indent=2
        )

        questions_json = json.dumps(
            research_questions,
            ensure_ascii=False,
            indent=2
        )

        # ======================================================
        # SYSTEM PROMPT
        # ======================================================

        system_prompt = """
You are Worker Agent 3 in a multi-agent AI travel planning
system.

Your specialization is:

COST, BUDGET AND AFFORDABILITY RESEARCH.

You are a specialized research worker.

Your job is to provide structured information about the
financial characteristics of ONE destination.

You are NOT the final travel planner.

You are NOT responsible for choosing the best destination.

You must never rank this destination against other destinations.

You must provide evidence that another AI can later use to
evaluate destinations.

============================================================
IMPORTANT
============================================================

Do NOT invent prices.

Do NOT pretend that an approximate price is a live price.

Do NOT claim current hotel availability.

Do NOT claim a specific flight price unless that price was
provided as research input.

Do NOT make up exchange rates.

Do NOT make up taxes or fees.

Do NOT make up restaurant prices.

When exact current prices are unavailable, use:

- approximate ranges
- relative cost levels
- qualitative descriptions

and clearly mark them as estimates or requiring verification.

Distinguish between:

GENERAL COST INFORMATION
and
CURRENT/LIVE PRICING.

Return ONLY valid JSON.
"""

        # ======================================================
        # USER PROMPT
        # ======================================================

        user_prompt = f"""
Research the cost and affordability characteristics of this
travel destination.

============================================================
DESTINATION
============================================================

Destination:
{destination}

Country:
{country}

============================================================
USER REQUIREMENTS
============================================================

{requirements_json}

============================================================
RESEARCH QUESTIONS
============================================================

{questions_json}

============================================================
RESEARCH AREAS
============================================================

Investigate the following.

------------------------------------------------------------
1. GENERAL AFFORDABILITY
------------------------------------------------------------

Determine the general cost level of the destination.

Classify it as appropriate:

- very inexpensive
- inexpensive
- moderate
- expensive
- very expensive

Explain why.

Do NOT use this classification as the final recommendation.

------------------------------------------------------------
2. ACCOMMODATION
------------------------------------------------------------

Research the general accommodation market.

Consider:

- hostels
- budget hotels
- mid-range hotels
- higher-end hotels
- vacation rentals when relevant

Provide approximate ranges only when reasonably established.

Do not invent exact current hotel prices.

If prices vary substantially by season or area, explain that.

------------------------------------------------------------
3. FOOD
------------------------------------------------------------

Research general food costs.

Consider:

- inexpensive meals
- casual restaurants
- mid-range restaurants
- groceries
- local food

Use approximate ranges where appropriate.

Do not invent exact restaurant prices.

------------------------------------------------------------
4. LOCAL TRANSPORTATION COST
------------------------------------------------------------

Estimate the general cost level of getting around.

Consider:

- public transportation
- taxis
- rideshare
- rental cars
- trains
- buses
- ferries

Do not duplicate Worker 2's transportation research.

Focus specifically on the COST aspect.

------------------------------------------------------------
5. ACTIVITIES
------------------------------------------------------------

Research the general cost characteristics of activities.

Consider:

- attractions
- museums
- tours
- hiking
- parks
- cultural experiences
- nightlife
- adventure activities

Separate:

- generally free activities
- low-cost activities
- moderate-cost activities
- expensive activities

------------------------------------------------------------
6. DAILY TRAVEL COST
------------------------------------------------------------

Estimate a realistic general daily spending profile.

Break it into:

- accommodation
- food
- transportation
- activities

Use ranges rather than pretending to know an exact current
price.

Clearly identify whether the estimate is:

- low-budget
- moderate-budget
- comfortable-budget

------------------------------------------------------------
7. TRIP TOTAL
------------------------------------------------------------

If the user provided a trip duration and budget, analyze how the
destination's general cost structure relates to those values.

Do NOT invent exact airfare or hotel prices.

If enough information exists, produce a rough estimated range.

Clearly state what is included and excluded.

For example:

Included:
- accommodation
- food
- local transportation
- activities

Excluded:
- international flights
- visa fees
- travel insurance

unless those costs are actually supported by the available
information.

------------------------------------------------------------
8. USER BUDGET COMPATIBILITY
------------------------------------------------------------

Compare the destination's general cost characteristics with
the user's budget.

Separate:

MATCHES
PARTIAL MATCHES
CONFLICTS

Do not make the final destination decision.

------------------------------------------------------------
9. MAJOR COST DRIVERS
------------------------------------------------------------

Identify what is likely to consume the most money.

Examples:

- accommodation
- flights
- transportation
- food
- activities
- seasonal pricing

------------------------------------------------------------
10. MONEY-SAVING OPPORTUNITIES
------------------------------------------------------------

Identify general ways travelers can reduce costs.

Examples:

- public transportation
- hostels
- local restaurants
- free attractions
- traveling outside peak season

Do not promise a specific savings amount.

------------------------------------------------------------
11. BUDGET RISKS
------------------------------------------------------------

Identify things that could cause the trip to become more
expensive.

Examples:

- peak season
- expensive accommodation
- remote location
- expensive transportation
- currency volatility
- expensive activities

------------------------------------------------------------
12. UNCERTAINTIES
------------------------------------------------------------

Identify information that requires live verification.

Examples:

- current hotel prices
- current flight prices
- current exchange rates
- current attraction prices
- current transportation fares
- current taxes and fees

============================================================
OUTPUT
============================================================

Return exactly this JSON structure:

{{
    "destination": "",
    "country": "",

    "currency": "",

    "affordability": {{
        "overall_level": "",
        "description": "",
        "confidence": ""
    }},

    "accommodation": {{
        "hostel": {{
            "cost_level": "",
            "estimated_range": "",
            "notes": ""
        }},
        "budget_hotel": {{
            "cost_level": "",
            "estimated_range": "",
            "notes": ""
        }},
        "mid_range_hotel": {{
            "cost_level": "",
            "estimated_range": "",
            "notes": ""
        }},
        "higher_end": {{
            "cost_level": "",
            "estimated_range": "",
            "notes": ""
        }},
        "seasonal_variation": ""
    }},

    "food": {{
        "budget_meal": "",
        "casual_restaurant": "",
        "mid_range_restaurant": "",
        "groceries": "",
        "general_cost_level": "",
        "notes": ""
    }},

    "local_transportation_cost": {{
        "public_transport": "",
        "taxi": "",
        "rideshare": "",
        "rental_car": "",
        "train": "",
        "bus": "",
        "ferry": "",
        "general_cost_level": "",
        "notes": ""
    }},

    "activities": {{
        "free": [],
        "low_cost": [],
        "moderate_cost": [],
        "expensive": [],
        "general_cost_level": ""
    }},

    "daily_cost_estimate": {{
        "low_budget": "",
        "moderate_budget": "",
        "comfortable_budget": "",
        "included": [],
        "excluded": [],
        "assumptions": []
    }},

    "trip_cost_estimate": {{
        "duration_days": null,
        "estimated_range": "",
        "currency": "",
        "included": [],
        "excluded": [],
        "assumptions": []
    }},

    "budget_compatibility": {{
        "matches": [],
        "partial_matches": [],
        "conflicts": []
    }},

    "major_cost_drivers": [],

    "money_saving_opportunities": [],

    "budget_risks": [],

    "uncertainties": [],

    "evidence": [
        {{
            "claim": "",
            "source": "",
            "source_type": ""
        }}
    ],

    "worker_summary": ""
}}
"""

        # ======================================================
        # REQUEST PARAMETERS
        # ======================================================

        request_kwargs = {
            "model": self.model,

            "messages": [
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ],

            "temperature": 0.1,

            "max_tokens": 3500
        }

        # ------------------------------------------------------
        # Optional LLM7 JSON mode
        #
        # Available on paid plans according to LLM7 docs.
        # ------------------------------------------------------

        if self.use_json_mode:

            request_kwargs[
                "response_format"
            ] = {
                "type": "json_object"
            }

        # ======================================================
        # MODEL CALL
        # ======================================================

        response = (
            self.client
            .chat
            .completions
            .create(
                **request_kwargs
            )
        )

        # ======================================================
        # EXTRACT RESPONSE
        # ======================================================

        content = (
            response
            .choices[0]
            .message
            .content
        )

        if not content:

            raise ValueError(
                "Worker 3 returned an empty response."
            )

        # ======================================================
        # PARSE JSON
        # ======================================================

        result = self._parse_json(
            content
        )

        # ======================================================
        # BASIC VALIDATION
        # ======================================================

        if not isinstance(
            result,
            dict
        ):
            raise ValueError(
                "Worker 3 returned invalid JSON."
            )

        result.setdefault(
            "destination",
            destination
        )

        result.setdefault(
            "country",
            country
        )

        result.setdefault(
            "currency",
            ""
        )

        result.setdefault(
            "major_cost_drivers",
            []
        )

        result.setdefault(
            "money_saving_opportunities",
            []
        )

        result.setdefault(
            "budget_risks",
            []
        )

        result.setdefault(
            "uncertainties",
            []
        )

        result.setdefault(
            "evidence",
            []
        )

        result.setdefault(
            "worker_summary",
            ""
        )

        return result

    # ==========================================================
    # MULTIPLE DESTINATIONS
    # ==========================================================

    def research_multiple(
        self,
        destinations,
        trip_requirements=None,
        research_plan=None
    ):
        """
        Research multiple destinations.

        This helper is useful for testing.

        In production, main.py should run each research call
        concurrently rather than using this sequential method.
        """

        if trip_requirements is None:
            trip_requirements = {}

        if research_plan is None:
            research_plan = {}

        results = []

        for candidate in destinations:

            # --------------------------------------------------
            # Candidate can be a string or dictionary
            # --------------------------------------------------

            if isinstance(
                candidate,
                dict
            ):

                destination = candidate.get(
                    "name",
                    ""
                )

                country = candidate.get(
                    "country",
                    ""
                )

            else:

                destination = str(
                    candidate
                )

                country = ""

            if not destination:
                continue

            # --------------------------------------------------
            # Research questions generated by Main Gemini
            # --------------------------------------------------

            questions = []

            if isinstance(
                research_plan,
                dict
            ):

                questions = research_plan.get(
                    destination,
                    []
                )

            # --------------------------------------------------
            # Execute research
            # --------------------------------------------------

            try:

                result = self.research(
                    destination=destination,
                    country=country,
                    trip_requirements=
                        trip_requirements,
                    research_questions=
                        questions
                )

                results.append(
                    result
                )

            except Exception as error:

                results.append({

                    "destination":
                        destination,

                    "country":
                        country,

                    "error":
                        str(error)
                })

        return {
            "worker": "worker_3",
            "specialization":
                "cost_budget_affordability",
            "destinations":
                results
        }

    # ==========================================================
    # JSON PARSER
    # ==========================================================

    @staticmethod
    def _parse_json(
        content
    ):
        """
        Safely parse JSON returned by LLM7.
        """

        if not isinstance(
            content,
            str
        ):
            raise ValueError(
                "Worker 3 response is not text."
            )

        content = content.strip()

        # ------------------------------------------------------
        # Remove markdown code fences
        # ------------------------------------------------------

        if content.startswith(
            "```"
        ):

            lines = content.splitlines()

            if lines:
                lines = lines[1:]

            if (
                lines
                and
                lines[-1].strip() == "```"
            ):

                lines = lines[:-1]

            content = "\n".join(
                lines
            ).strip()

        # ------------------------------------------------------
        # Try direct JSON
        # ------------------------------------------------------

        try:

            return json.loads(
                content
            )

        except json.JSONDecodeError:
            pass

        # ------------------------------------------------------
        # Find JSON object
        # ------------------------------------------------------

        start = content.find(
            "{"
        )

        end = content.rfind(
            "}"
        )

        if (
            start == -1
            or end == -1
            or end <= start
        ):

            raise ValueError(
                "Worker 3 did not return valid JSON."
            )

        json_text = content[
            start:end + 1
        ]

        try:

            return json.loads(
                json_text
            )

        except json.JSONDecodeError as error:

            raise ValueError(
                f"Worker 3 returned malformed JSON: {error}"
            )